# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "reverse": "01_xpython.ipynb",
         "distinct": "01_xpython.ipynb"}

modules = ["core.py",
           "xpython.py"]

doc_url = "https://rvolykh.github.io/nb/"

git_url = "https://github.com/rvolykh/nb/tree/master/"

def custom_doc_links(name): return None
