# AUTOGENERATED! DO NOT EDIT! File to edit: 01_xpython.ipynb (unless otherwise specified).

__all__ = ['reverse', 'distinct']

# Cell
def reverse(str):
    """Reverse string"""
    return str[::-1]

# Cell
def distinct(input):
    """Remove duplicates"""
    return list(set(input))